#' Perform CCPLS
#'
#' Arguments for cellCellReg
#' @param exp_mat A matrix object containing expression values. The rows represent cells. The columns represent genes. Row names and column names correspond to cell IDs and gene symbols, respectively.
#' @param coord_mat A matrix object containing cell IDs, x and y coordinates. The rows represent cells. The first column contains cell IDs and the second and subsequent columns contain x and y coordinates.
#' @param annot_mat A matrix object containing cell IDs and cell type labels. The rows represent cells. The first column contains cell IDs and the second column contains cell type labels.
#' @param output_dir A string. Full path of directory for saving outputs generated by CCPLS.
#' @param HVG_extract_num A number. Option for specifying extraction number of HVGs. The value is set as 2,000 in the default setting.
#'
#' @export
#'
cellCellReg <- function(exp_mat,
                        coord_mat,
                        annot_mat,
                        output_dir,
                        HVG_extract_num = 2000){

  if (!file.exists(output_dir)){
    dir.create(file.path(output_dir))
  }

  # For development
  HVG_opt <- TRUE
  dev_opt <- "pls"

  ### Make feature matrix
  res.make.features <- cellCellRegMakeFet(coord_mat = coord_mat,
                                          annot_mat = annot_mat)

  ### Separate into each cell type
  res.sep.mat <- cellCellRegSepMat(exp_mat = exp_mat,
                                   fet_mat = res.make.features$fet_mat_unnorm,
                                   annot_mat = annot_mat,
                                   annot_score_mat = res.make.features$annot_score_mat,
                                   HVG_opt = HVG_opt,
                                   HVG_extract_num = HVG_extract_num)

  ### Estimate by PLS regression
  res.estimate <- cellCellRegEst(fet_mat_orig = res.make.features$fet_mat_unnorm,
                                 annot_score_mat = res.make.features$annot_score_mat,
                                 exp_mat_sep_list = res.sep.mat$exp_mat_sep_list,
                                 fet_mat_sep_list = res.sep.mat$fet_mat_sep_list,
                                 estimate_cell_type_opt = "all",
                                 cell_type_list = res.sep.mat$cell_type_list,
                                 dev_opt = dev_opt)

  ### Select significant variable
  res.sel.var <- cellCellRegSelVar(res.estimate = res.estimate,
                                   res.sep.mat = res.sep.mat,
                                   HVG_extract_num = HVG_extract_num,
                                   dev_opt = "kmeans")

  ### Get heatmap object
  res.heatmap <- cellCellRegHeatmap(res.sel.var = res.sel.var,
                                    output_dir = output_dir)

  ### Get bipartite graph object
  res.graph <- cellCellRegGraph(res.sel.var = res.sel.var,
                                output_dir = output_dir)

  
  return(list(res.make.features = res.make.features,
              res.sep.mat = res.sep.mat,
              res.estimate = res.estimate,
              res.sel.var = res.sel.var,
              res.heatmap = res.heatmap,
              res.graph = res.graph))

}